apiVersion: apps/v1
kind: Deployment
metadata:
  name: growth-server-deployment
  labels:
    app: growth-server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growth-server-deployment
  template:
    metadata:
      labels:
        app: growth-server-deployment
    spec:
      serviceAccountName: cloud-sql-postgres-databasesql
      containers:
        - name: growth-server
          image: harshalbadade/growth-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: INSTANCE_CONNECTION_NAME
              value: "my-growth-project-417918:europe-west3:growth-postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: database
        - name: cloud-sql-proxy
          # This uses the latest version of the Cloud SQL proxy
          # It is recommended to use a specific version for production environments.
          # See: https://github.com/GoogleCloudPlatform/cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            # - "--private-ip"

            # If you are not connecting with Automatic IAM, you can delete
            # the following flag.
            # - "--auto-iam-authn"

            # tcp should be set to the port the proxy should listen on
            # and should match the DB_PORT value set above.
            # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
            - "--port=5432"
            - "my-growth-project-417918:europe-west3:growth-postgres"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: growth-server-service
  name: growth-server-service
  namespace: default
spec:
  selector:
    app: growth-server-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
  type: LoadBalancer
