apiVersion: apps/v1
kind: Deployment
metadata:
  name: growth-server-deployment
  labels:
    app: growth-server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growth-server-deployment
  template:
    metadata:
      labels:
        app: growth-server-deployment
    spec:
      containers:
        - name: growth-server
          image: harshalbadade/growth-server:latest
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: growth-server-service
  name: growth-server-service
  namespace: default
spec:
  selector:
    app: growth-server-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
  type: LoadBalancer
