name: Continous Integration Pipeline

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # refer the secrets from environment of production
    environment:
      name: production
      url: "https://github.com"

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: Setup Node JS - ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build

      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/growth-server .
          docker tag ${{ secrets.DOCKER_USERNAME }}/growth-server ${{ secrets.DOCKER_USERNAME }}/growth-server:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/growth-server

      # - name: Setup Docker QEMU
      #   run: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   run: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Dockerize
      #   run: docker build -t growth-server .

      # - name: Build and Push to Docker
      #   uses: docker/build-push-action@v5
      #   with:
      #     # context: .
      #     # file: ./Dockerfile
      #     push: true
      #     tags: harshalbadade/growth-server:latest
